#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Shunsuke Shibata
# SPDX-License-Identifier: BSD-3-Clause

import random   #ランダムな動きをするモジュール
import itertools   #無限ループのために使うイテレータツール

responses = ["私は上田先生が大好きです。", "私は上田先生を愛しています。", "私は０点を取りたくないです。",
        "私は単位が欲しいです。", "ちんこ！", "私は地雷を踏みたくないです", ]

print("ドキドキ柴田君：何かコメントをして私とお話ししましょう。")  #挨拶

# for文で無限ループ
for _ in itertools.count():     #無限に値を生成するイテレータ
    user_input = input("あなた:")
    if user_input in ["柴田君もういいよ"]: #柴田君もういいよでループ抜ける
        print("ドキドキ柴田君:うんこ！")
        break
    else:
        print("ドキドキ柴田君:", random.choice(responses)) #ランダムな返答を生成
